site :opscode

cookbook 'yum'
cookbook 'nginx'
cookbook 'python'
cookbook 'selinux'
cookbook 'openssh'

# The following cookbooks are used for chef-rails-dev-box.
cookbook 'apt'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'database'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build'
